#服务器配置
server:
  port: 8999
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 3000
      cookie:
        name: paichi

#spring配置
spring:
  application:
    name: paichi
  redis:
#    host: 39.98.65.221
    host: 121.5.9.16
    port: 6379
    timeout: 60000
#配置Oracle数据源
  datasource:
    druid:
      url: jdbc:mysql://121.5.9.16:3306/paichi?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: nevergiveup?
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//192.168.1.6:1521/helowin
#    username: PAICHI
#    password: paichi
#thymeleaf配置
  thymeleaf:
    #页面热加载
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
#配置静态资源
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
#热加载
  devtools:
    restart:
      enabled: true

  #邮箱
  mail:
    username: liulebinn@163.com
    password: llb1998
    host: smtp.163.com
    default-encoding: utf-8
    #    配置邮件服务器的端口，默认25端口，但是阿里云和腾讯云服务器为了安全关闭端口
    port: 465

    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl.enable: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          starttls.enable: true
          socketFactory.port: 465　
          port: 465

#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false
##STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
#        starttls:
#          enable: true
#          required: true
#邮件发件人
mail:
  fromMail:
    addr: liulebinn@163.com

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.paichi.modules
  mapper-locations: classpath:mapper/*/*Mapper.xml
#  二级缓存
  configuration:
    cache-enabled: true
#    配置驼峰命名
    map-underscore-to-camel-case: true
#    允许返回字段值为null
    call-setters-on-nulls: true

#日志配置
logging:
  level:
    com.paichi: debug
    org.springframework: WARN
    org.spring.springboot.dao: error

# 文件系统
minio:
  url: http://121.5.9.16:9000
  accessKey: minio
  secretKey: nevergiveup?
  bucketName: paichi




